# Generated by Django 4.0.3 on 2022-03-22 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banka_adi', models.CharField(max_length=30, unique=True)),
                ('durum', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banka',
                'verbose_name_plural': 'Bankalar',
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
                ('toplam_yatirim', models.DecimalField(decimal_places=5, max_digits=20)),
                ('toplam_cekim', models.DecimalField(decimal_places=5, max_digits=20)),
                ('durum', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FHesapirma',
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.CreateModel(
            name='Hesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sube_kodu', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('hesap_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(12)])),
                ('iban_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(24)])),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('durum', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('max_limit', models.DecimalField(decimal_places=5, max_digits=20)),
                ('tc_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(11)])),
                ('banka_adi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hesap', to='dashboard.banka')),
            ],
            options={
                'verbose_name': 'Hesap',
                'verbose_name_plural': 'Hesaplar',
            },
        ),
    ]
