# Generated by Django 4.0.3 on 2022-03-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmalar'},
        ),
        migrations.RemoveField(
            model_name='firma',
            name='toplam_cekim',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='toplam_yatirim',
        ),
        migrations.AlterField(
            model_name='firma',
            name='durum',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], default='Aktif', max_length=10),
        ),
        migrations.AlterField(
            model_name='hesap',
            name='durum',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], default='Aktif', max_length=10),
        ),
    ]
