# Generated by Django 4.0.3 on 2022-03-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='islem_tipi',
        ),
        migrations.AddField(
            model_name='islemtipi',
            name='firma_adi',
            field=models.ManyToManyField(related_name='islem_tipi', to='dashboard.firma'),
        ),
    ]
