# Generated by Django 4.0.3 on 2022-03-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_firma_options_remove_firma_toplam_cekim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslemTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tipi', models.CharField(max_length=50, unique=True)),
                ('durum', models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], default='Aktif', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='firma',
            name='islem_tipi',
            field=models.ManyToManyField(related_name='firma', to='dashboard.islemtipi'),
        ),
    ]
