# Generated by Django 4.0.3 on 2022-03-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_islemtipi_firma_islem_tipi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='islemtipi',
            options={'verbose_name': 'Islem Tipi', 'verbose_name_plural': 'Islem Tipleri'},
        ),
        migrations.AddField(
            model_name='hesap',
            name='yontem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.islemtipi'),
        ),
        migrations.CreateModel(
            name='Yatirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('Onaylanmis', 'Onaylanmis'), ('Reddedilen', 'Reddedilen'), ('Bekleyen', 'Bekleyen')], default='Bekleyen', max_length=20)),
                ('yatirilan_tutar', models.DecimalField(decimal_places=5, max_digits=20)),
                ('modified_time', models.DateField(auto_now=True)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('firma_adi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yatirim', to='dashboard.firma')),
                ('yatirilan_hesap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yatirim_hesap', to='dashboard.hesap')),
            ],
            options={
                'verbose_name': 'Yatirim',
                'verbose_name_plural': 'Yatirimlar',
            },
        ),
    ]
