# Generated by Django 4.0.3 on 2022-03-26 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_islemtipi_firma_adi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='islemtipi',
            name='firma_adi',
        ),
        migrations.AddField(
            model_name='firma',
            name='islem_tipi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma', to='dashboard.islemtipi'),
        ),
    ]
