# Generated by Django 4.0.3 on 2022-03-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_islemtipi_firma_adi_firma_islem_tipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='komisyon_orani',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
